"""Native Bayesian inference and forecasting with composable Python workflows."""
from ._rustmc import *
from ._rustmc import __version__
from .evaluation import (
    BacktestFold, BacktestResult, backtest, crps, interval_score,
    naive_forecast, score_forecast, seasonal_naive, weighted_interval_score,
)
from .forecasting import (
    ForecastDraws, ForecastSession, NamedDesign, ScenarioForecast, forecast_scenarios,
)

# The public API, and nothing else.  Importing the two submodules below binds
# them as package attributes, so without this list `from rustmc import *` also
# hands out the `evaluation` and `forecasting` module objects -- layout, not
# API.  (`dir(rustmc)` still shows them: it reports the module dict and is not
# affected by `__all__`.  Tooling that honours `__all__` -- `import *`, Sphinx,
# most IDE completion -- is.)  `__version__` is deliberately absent: it stays
# importable by name, as dunders always do, but `import *` should not bind it.
#
# tests/test_namespace.py derives what belongs here from the extension's own
# exports and fails naming anything unlisted, so this list cannot silently rot.
__all__ = [
    "BacktestFold",
    "BacktestResult",
    "BatchFit",
    "BatchResult",
    "BayesianAR",
    "BayesianARFit",
    "BayesianARForecast",
    "BayesianAutoRegression",
    "BayesianDynamicGLM",
    "BayesianDynamicHurdleLogNormal",
    "BayesianDynamicNegativeBinomial",
    "BayesianDynamicPoisson",
    "BayesianForecastResult",
    "BayesianHierarchicalDynamicRegression",
    "BayesianHierarchicalForecast",
    "BayesianHierarchicalMean",
    "BayesianHierarchicalMeanFit",
    "BayesianHurdleLogNormal",
    "BayesianHurdleLogNormalFit",
    "BayesianHurdleLogNormalForecast",
    "BayesianLocalLevel",
    "BayesianLocalLevelFit",
    "BayesianLocalLinearTrend",
    "BayesianLocalLinearTrendFit",
    "BayesianRegressionFit",
    "BayesianRegressionForecast",
    "BayesianSeasonalForecast",
    "BayesianSeasonalLocalLevel",
    "BayesianSeasonalLocalLevelFit",
    "BayesianTrendForecast",
    "BoundModel",
    "CompiledModel",
    "DirichletMultinomialRunoff",
    "DynamicGLMFit",
    "DynamicGLMForecast",
    "Expr",
    "FitResult",
    "ForecastBatchFit",
    "ForecastBatchForecast",
    "ForecastDraws",
    "ForecastResult",
    "ForecastSession",
    "GaussianCoefficientPrior",
    "InferenceError",
    "InverseGammaPrior",
    "KalmanFilterResult",
    "KalmanSmootherResult",
    "LinearGaussianStateSpace",
    "ModelBuilder",
    "ModelSpec",
    "NamedDesign",
    "NormalInverseGammaPrior",
    "ParamRef",
    "ParameterError",
    "RunoffFit",
    "ScenarioForecast",
    "StateSpaceError",
    "StructuralComponent",
    "StructuralFit",
    "StructuralForecast",
    "StructuralModel",
    "VarianceParameter",
    "VectorParamRef",
    "backtest",
    "batch_sample",
    "crps",
    "forecast_cell_seed",
    "forecast_scenarios",
    "fourier_design",
    "hurdle_lognormal_logp",
    "interval_score",
    "naive_forecast",
    "sample",
    "sample_prior_predictive",
    "score_forecast",
    "seasonal_naive",
    "weighted_interval_score",
]
