"""Public native API types. Keep synchronized with python_bindings/src PyO3 declarations.

Update this file with native API changes and run tests/test_native_typing.py.

_FloatArray is a NumPy float64 ndarray. Forecast arrays retain chain/draw axes;
see the model-specific documentation for state, group, and horizon dimensions.
Inputs declared _FloatArray require native float64 ndarrays; ArrayLike/Sequence
inputs also accept compatible Python sequences. Optional ArviZ objects use Any
because ArviZ is an optional dependency.
"""
from typing import Any, Literal, Sequence, TypedDict, overload
import numpy as np
from numpy.typing import ArrayLike, NDArray

_FloatArray = NDArray[np.float64]
_UIntArray = NDArray[np.uint64]
_BoolArray = NDArray[np.bool_]
_ExpressionLike = float | ParamRef | Expr
_Data = dict[str, ArrayLike]
_Diagnostic = TypedDict(
    "_Diagnostic",
    {
        "name": str,
        "mean": float | None,
        "std": float | None,
        "hdi_3%": float | None,
        "hdi_97%": float | None,
        "ess_bulk": float | None,
        "ess_tail": float | None,
        "r_hat": float | None,
        "mcse_mean": float | None,
    },
)
__version__: str

class ParameterError(ValueError): ...
class StateSpaceError(ValueError): ...
class InferenceError(ValueError): ...


class BatchFit:
    @property
    def ids(self) -> list[str]: ...
    @property
    def errors(self) -> dict[str, str]: ...
    def get(self, id: str) -> BatchResult: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BatchResult: ...
    def __enter__(self) -> BatchFit: ...
    def __exit__(self, _exc_type: Any, _exc_value: Any, _traceback: Any) -> bool: ...
    def __repr__(self) -> str: ...

class BatchResult:
    @property
    def fit(self) -> FitResult: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    def summary(self) -> str: ...
    def transition_diagnostics(self) -> dict[str, Any]: ...
    def predict(
        self,
        data: _Data | None = None,
        seed: int = 42,
        expected: bool = False,
        sizes: dict[str, int] | None = None,
    ) -> dict[str, _FloatArray]: ...
    def get_samples_2d(self) -> dict[str, _FloatArray]: ...
    def mean(self) -> dict[str, float]: ...
    def std(self) -> dict[str, float]: ...
    def get_samples(self) -> dict[str, _FloatArray]: ...
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def accept_rate(self) -> float: ...
    @property
    def accept_rates(self) -> list[float]: ...
    @property
    def divergences(self) -> int: ...
    @property
    def divergences_per_chain(self) -> list[int]: ...
    def __repr__(self) -> str: ...

class BayesianARFit:
    def summary(self) -> str: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    @property
    def order(self) -> int: ...
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def time_count(self) -> int: ...
    @property
    def regression_count(self) -> int: ...
    @property
    def seed(self) -> int: ...
    def get_samples(self) -> dict[str, _FloatArray]: ...
    def forecast(self, steps: int, seed: int = 43) -> BayesianARForecast: ...
    def to_arviz(self) -> Any: ...
    def __repr__(self) -> str: ...

class BayesianARForecast:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def steps(self) -> int: ...
    @property
    def conditional_mean_samples(self) -> _FloatArray: ...
    @property
    def observation_samples(self) -> _FloatArray: ...
    @property
    def conditional_mean(self) -> _FloatArray: ...
    @property
    def observation_mean(self) -> _FloatArray: ...
    def conditional_mean_quantile(self, probability: float) -> _FloatArray: ...
    def observation_quantile(self, probability: float) -> _FloatArray: ...
    def conditional_mean_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    @property
    def uncertainty_kind(self) -> str: ...
    @property
    def interval_kind(self) -> str: ...
    def __repr__(self) -> str: ...

class BayesianAutoRegression:
    def fit_batch(
        self,
        observations: ArrayLike | Sequence[ArrayLike],
        ids: Sequence[str],
        *,
        models: Sequence[_ForecastPreset | None] | None = None,
        exog: Sequence[ArrayLike | None] | None = None,
        coefficient_priors: Sequence[GaussianCoefficientPrior | None] | None = None,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        threads: int = 1,
        chunk_size: int = 64,
        errors: Literal["raise", "collect"] = "raise",
    ) -> ForecastBatchFit: ...
    def __init__(self, order: int, prior: NormalInverseGammaPrior) -> None: ...
    @property
    def order(self) -> int: ...
    @property
    def prior(self) -> NormalInverseGammaPrior: ...
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        seed: int = 42,
    ) -> BayesianARFit: ...
    def __repr__(self) -> str: ...

class BayesianDynamicGLM:
    def prior_predictive(
        self,
        steps: int,
        *,
        groups: int = 1,
        exog: ArrayLike | None = None,
        exposure: ArrayLike | None = None,
        chains: int = 1,
        draws: int = 1000,
        seed: int = 42,
    ) -> DynamicGLMForecast: ...
    def __init__(
        self,
        family: Literal["poisson", "negative_binomial", "hurdle_lognormal", "gaussian"] = "poisson",
        *,
        initial_mean: float = 0.0,
        occurrence_initial_mean: float = 0.0,
        coefficient_sd: float = 1.0,
        group_sd: float = 0.5,
        process_sd: float = 0.1,
        shared_process_sd: float = 0.0,
        observation_sd: float = 1.0,
        dispersion: float = 5.0,
    ) -> None: ...
    def fit(
        self,
        y: ArrayLike,
        *,
        exog: ArrayLike | None = None,
        exposure: ArrayLike | None = None,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 1000,
        thin: int = 1,
        seed: int = 42,
    ) -> DynamicGLMFit: ...

class BayesianForecastResult:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def steps(self) -> int: ...
    @property
    def state_samples(self) -> _FloatArray: ...
    @property
    def observation_samples(self) -> _FloatArray: ...
    @property
    def state_mean(self) -> _FloatArray: ...
    @property
    def observation_mean(self) -> _FloatArray: ...
    def state_quantile(self, probability: float) -> _FloatArray: ...
    def observation_quantile(self, probability: float) -> _FloatArray: ...
    def state_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    @property
    def uncertainty_kind(self) -> str: ...
    @property
    def interval_kind(self) -> str: ...
    def __repr__(self) -> str: ...

class BayesianHierarchicalForecast:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def program_count(self) -> int: ...
    @property
    def group_count(self) -> int: ...
    @property
    def steps(self) -> int: ...
    @property
    def group_index(self) -> list[int]: ...
    @property
    def program_names(self) -> list[str]: ...
    @property
    def group_names(self) -> list[str]: ...
    @property
    def state_samples(self) -> _FloatArray: ...
    @property
    def observation_samples(self) -> _FloatArray: ...
    @property
    def group_observation_samples(self) -> _FloatArray: ...
    @property
    def total_observation_samples(self) -> _FloatArray: ...
    @property
    def state_mean(self) -> _FloatArray: ...
    @property
    def observation_mean(self) -> _FloatArray: ...
    def state_quantile(self, probability: float) -> _FloatArray: ...
    def observation_quantile(self, probability: float) -> _FloatArray: ...
    def interval(self, level: float) -> tuple[_FloatArray, _FloatArray]: ...
    def state_interval(self, level: float) -> tuple[_FloatArray, _FloatArray]: ...
    @property
    def uncertainty_kind(self) -> str: ...
    @property
    def interval_kind(self) -> str: ...
    def __repr__(self) -> str: ...

class BayesianHierarchicalMean:
    def __init__(
        self,
        group_variance_prior: InverseGammaPrior,
        program_variance_prior: InverseGammaPrior,
        observation_variance_prior: InverseGammaPrior,
        population_mean_prior: float = 0.0,
        population_variance_prior: float = 100.0,
    ) -> None: ...
    @property
    def population_mean_prior(self) -> float: ...
    @property
    def population_variance_prior(self) -> float: ...
    @property
    def group_variance_prior(self) -> InverseGammaPrior: ...
    @property
    def program_variance_prior(self) -> InverseGammaPrior: ...
    @property
    def observation_variance_prior(self) -> InverseGammaPrior: ...
    def fit(
        self,
        series: _FloatArray,
        group_index: Sequence[int],
        program_names: Sequence[str] | None = None,
        group_names: Sequence[str] | None = None,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
    ) -> BayesianHierarchicalMeanFit: ...
    def __repr__(self) -> str: ...

class BayesianHierarchicalMeanFit:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def program_count(self) -> int: ...
    @property
    def group_count(self) -> int: ...
    @property
    def time_counts(self) -> list[int]: ...
    @property
    def observed_counts(self) -> list[int]: ...
    @property
    def total_observed_count(self) -> int: ...
    @property
    def group_index(self) -> list[int]: ...
    @property
    def program_names(self) -> list[str]: ...
    @property
    def group_names(self) -> list[str]: ...
    @property
    def warmup(self) -> int: ...
    @property
    def thin(self) -> int: ...
    @property
    def inference_method(self) -> str: ...
    def get_samples(self) -> dict[str, _FloatArray]: ...
    def summary(self) -> str: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    def forecast(self, steps: int, seed: int = 43) -> BayesianHierarchicalForecast: ...
    def __repr__(self) -> str: ...

class BayesianHurdleLogNormal:
    def fit_batch(
        self,
        observations: ArrayLike | Sequence[ArrayLike],
        ids: Sequence[str],
        *,
        models: Sequence[_ForecastPreset | None] | None = None,
        exog: Sequence[ArrayLike | None] | None = None,
        coefficient_priors: Sequence[GaussianCoefficientPrior | None] | None = None,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        threads: int = 1,
        chunk_size: int = 64,
        errors: Literal["raise", "collect"] = "raise",
    ) -> ForecastBatchFit: ...
    def __init__(
        self,
        process_variance_prior: InverseGammaPrior,
        observation_variance_prior: InverseGammaPrior,
        occurrence_alpha: float = 1.0,
        occurrence_beta: float = 1.0,
        initial_log_level: float = 0.0,
        initial_variance: float = 1.0,
        process_variance_upper: float = 1.0,
        observation_variance_upper: float = 4.0,
    ) -> None: ...
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
    ) -> BayesianHurdleLogNormalFit: ...
    @property
    def process_variance_upper(self) -> float: ...
    @property
    def observation_variance_upper(self) -> float: ...
    def __repr__(self) -> str: ...

class BayesianHurdleLogNormalFit:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def time_count(self) -> int: ...
    @property
    def observed_count(self) -> int: ...
    @property
    def positive_count(self) -> int: ...
    @property
    def severity_informed_by_data(self) -> bool: ...
    @property
    def warmup(self) -> int: ...
    @property
    def thin(self) -> int: ...
    def get_samples_2d(self) -> dict[str, _FloatArray]: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    def summary(self) -> str: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    def forecast(self, steps: int, seed: int = 43) -> BayesianHurdleLogNormalForecast: ...
    def to_arviz(self) -> Any: ...

class BayesianHurdleLogNormalForecast:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def steps(self) -> int: ...
    @property
    def observation_samples(self) -> _FloatArray: ...
    @property
    def mean_samples(self) -> _FloatArray: ...
    @property
    def positive_mean_samples(self) -> _FloatArray: ...
    @property
    def observation_mean(self) -> _FloatArray: ...
    @property
    def mean(self) -> _FloatArray: ...
    @property
    def cumulative_observation_samples(self) -> _FloatArray: ...
    def interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def mean_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def cumulative_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    @property
    def uncertainty_kind(self) -> str: ...
    @property
    def interval_kind(self) -> str: ...

class BayesianLocalLevel:
    def fit_batch(
        self,
        observations: ArrayLike | Sequence[ArrayLike],
        ids: Sequence[str],
        *,
        models: Sequence[_ForecastPreset | None] | None = None,
        exog: Sequence[ArrayLike | None] | None = None,
        coefficient_priors: Sequence[GaussianCoefficientPrior | None] | None = None,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        threads: int = 1,
        chunk_size: int = 64,
        errors: Literal["raise", "collect"] = "raise",
    ) -> ForecastBatchFit: ...
    def __init__(
        self,
        process_variance_prior: InverseGammaPrior,
        observation_variance_prior: InverseGammaPrior,
        initial_mean: float = 0.0,
        initial_variance: float = 100.0,
    ) -> None: ...
    @property
    def initial_mean(self) -> float: ...
    @property
    def initial_variance(self) -> float: ...
    @property
    def process_variance_prior(self) -> InverseGammaPrior: ...
    @property
    def observation_variance_prior(self) -> InverseGammaPrior: ...
    @overload
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        *,
        exog: None = None,
        coefficient_prior: GaussianCoefficientPrior | None = None,
    ) -> BayesianLocalLevelFit: ...
    @overload
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        *,
        exog: _FloatArray,
        coefficient_prior: GaussianCoefficientPrior,
    ) -> BayesianRegressionFit: ...
    @overload
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        *,
        exog: _FloatArray | None = None,
        coefficient_prior: GaussianCoefficientPrior | None = None,
    ) -> BayesianLocalLevelFit | BayesianRegressionFit: ...
    def __repr__(self) -> str: ...

class BayesianLocalLevelFit:
    def summary(self) -> str: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def observed_count(self) -> int: ...
    @property
    def time_count(self) -> int: ...
    @property
    def warmup(self) -> int: ...
    @property
    def thin(self) -> int: ...
    def get_samples_2d(self) -> dict[str, _FloatArray]: ...
    def forecast(self, steps: int, seed: int = 43) -> BayesianForecastResult: ...
    def to_arviz(self) -> Any: ...
    def __repr__(self) -> str: ...

class BayesianLocalLinearTrend:
    def fit_batch(
        self,
        observations: ArrayLike | Sequence[ArrayLike],
        ids: Sequence[str],
        *,
        models: Sequence[_ForecastPreset | None] | None = None,
        exog: Sequence[ArrayLike | None] | None = None,
        coefficient_priors: Sequence[GaussianCoefficientPrior | None] | None = None,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        threads: int = 1,
        chunk_size: int = 64,
        errors: Literal["raise", "collect"] = "raise",
    ) -> ForecastBatchFit: ...
    def __init__(
        self,
        level_variance_prior: InverseGammaPrior,
        slope_variance_prior: InverseGammaPrior,
        observation_variance_prior: InverseGammaPrior,
        initial_level: float = 0.0,
        initial_slope: float = 0.0,
        initial_level_variance: float = 100.0,
        initial_slope_variance: float = 10.0,
        initial_level_slope_covariance: float = 0.0,
    ) -> None: ...
    @property
    def initial_level(self) -> float: ...
    @property
    def initial_slope(self) -> float: ...
    @property
    def initial_covariance(self) -> _FloatArray: ...
    @property
    def level_variance_prior(self) -> InverseGammaPrior: ...
    @property
    def slope_variance_prior(self) -> InverseGammaPrior: ...
    @property
    def observation_variance_prior(self) -> InverseGammaPrior: ...
    @overload
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        *,
        exog: None = None,
        coefficient_prior: GaussianCoefficientPrior | None = None,
    ) -> BayesianLocalLinearTrendFit: ...
    @overload
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        *,
        exog: _FloatArray,
        coefficient_prior: GaussianCoefficientPrior,
    ) -> BayesianRegressionFit: ...
    @overload
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        *,
        exog: _FloatArray | None = None,
        coefficient_prior: GaussianCoefficientPrior | None = None,
    ) -> BayesianLocalLinearTrendFit | BayesianRegressionFit: ...
    def __repr__(self) -> str: ...

class BayesianLocalLinearTrendFit:
    def summary(self) -> str: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def time_count(self) -> int: ...
    @property
    def observed_count(self) -> int: ...
    @property
    def warmup(self) -> int: ...
    @property
    def thin(self) -> int: ...
    def get_samples_2d(self) -> dict[str, _FloatArray]: ...
    def forecast(self, steps: int, seed: int = 43) -> BayesianTrendForecast: ...
    def to_arviz(self) -> Any: ...
    def __repr__(self) -> str: ...

class BayesianRegressionFit:
    def summary(self) -> str: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def time_count(self) -> int: ...
    @property
    def observed_count(self) -> int: ...
    @property
    def warmup(self) -> int: ...
    @property
    def thin(self) -> int: ...
    def get_samples_2d(self) -> dict[str, _FloatArray]: ...
    def forecast(
        self,
        steps: int,
        seed: int = 43,
        *,
        exog: _FloatArray | None = None,
    ) -> BayesianRegressionForecast: ...
    def to_arviz(self) -> Any: ...

class BayesianRegressionForecast:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def steps(self) -> int: ...
    @property
    def observation_samples(self) -> _FloatArray: ...
    @property
    def cumulative_observation_samples(self) -> _FloatArray: ...
    @property
    def state_samples(self) -> _FloatArray: ...
    @property
    def level_samples(self) -> _FloatArray: ...
    @property
    def seasonal_samples(self) -> _FloatArray: ...
    @property
    def slope_samples(self) -> _FloatArray: ...
    @property
    def regression_samples(self) -> _FloatArray: ...
    @property
    def mean_samples(self) -> _FloatArray: ...
    @property
    def observation_mean(self) -> _FloatArray: ...
    @property
    def cumulative_observation_mean(self) -> _FloatArray: ...
    def observation_interval(self, probability: float = 0.9) -> tuple[_FloatArray, _FloatArray]: ...
    def cumulative_observation_interval(
        self,
        probability: float = 0.9,
    ) -> tuple[_FloatArray, _FloatArray]: ...
    def interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def cumulative_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    @property
    def uncertainty_kind(self) -> str: ...
    @property
    def interval_kind(self) -> str: ...

class BayesianSeasonalForecast:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def steps(self) -> int: ...
    @property
    def level_samples(self) -> _FloatArray: ...
    @property
    def seasonal_samples(self) -> _FloatArray: ...
    @property
    def observation_samples(self) -> _FloatArray: ...
    @property
    def cumulative_observation_samples(self) -> _FloatArray: ...
    @property
    def level_mean(self) -> _FloatArray: ...
    @property
    def seasonal_mean(self) -> _FloatArray: ...
    @property
    def observation_mean(self) -> _FloatArray: ...
    @property
    def cumulative_observation_mean(self) -> _FloatArray: ...
    def level_quantile(self, probability: float) -> _FloatArray: ...
    def seasonal_quantile(self, probability: float) -> _FloatArray: ...
    def observation_quantile(self, probability: float) -> _FloatArray: ...
    def cumulative_observation_quantile(self, probability: float) -> _FloatArray: ...
    def interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def cumulative_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    @property
    def uncertainty_kind(self) -> str: ...
    @property
    def interval_kind(self) -> str: ...
    def __repr__(self) -> str: ...

class BayesianSeasonalLocalLevel:
    def fit_batch(
        self,
        observations: ArrayLike | Sequence[ArrayLike],
        ids: Sequence[str],
        *,
        models: Sequence[_ForecastPreset | None] | None = None,
        exog: Sequence[ArrayLike | None] | None = None,
        coefficient_priors: Sequence[GaussianCoefficientPrior | None] | None = None,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        threads: int = 1,
        chunk_size: int = 64,
        errors: Literal["raise", "collect"] = "raise",
    ) -> ForecastBatchFit: ...
    def __init__(
        self,
        period: int,
        level_variance_prior: InverseGammaPrior,
        seasonal_variance_prior: InverseGammaPrior,
        observation_variance_prior: InverseGammaPrior,
        initial_level: float = 0.0,
        initial_seasonal_effects: ArrayLike | None = None,
        initial_level_variance: float = 100.0,
        initial_seasonal_variance: float = 10.0,
    ) -> None: ...
    @property
    def period(self) -> int: ...
    @property
    def initial_seasonal_effects(self) -> _FloatArray: ...
    @overload
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        *,
        exog: None = None,
        coefficient_prior: GaussianCoefficientPrior | None = None,
    ) -> BayesianSeasonalLocalLevelFit: ...
    @overload
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        *,
        exog: _FloatArray,
        coefficient_prior: GaussianCoefficientPrior,
    ) -> BayesianRegressionFit: ...
    @overload
    def fit(
        self,
        observations: _FloatArray,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        *,
        exog: _FloatArray | None = None,
        coefficient_prior: GaussianCoefficientPrior | None = None,
    ) -> BayesianSeasonalLocalLevelFit | BayesianRegressionFit: ...
    def __repr__(self) -> str: ...

class BayesianSeasonalLocalLevelFit:
    def summary(self) -> str: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def period(self) -> int: ...
    @property
    def time_count(self) -> int: ...
    @property
    def observed_count(self) -> int: ...
    @property
    def warmup(self) -> int: ...
    @property
    def thin(self) -> int: ...
    def get_samples_2d(self) -> dict[str, _FloatArray]: ...
    def forecast(self, steps: int, seed: int = 43) -> BayesianSeasonalForecast: ...
    def to_arviz(self) -> Any: ...
    def __repr__(self) -> str: ...

class BayesianTrendForecast:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def steps(self) -> int: ...
    @property
    def level_samples(self) -> _FloatArray: ...
    @property
    def slope_samples(self) -> _FloatArray: ...
    @property
    def observation_samples(self) -> _FloatArray: ...
    @property
    def level_mean(self) -> _FloatArray: ...
    @property
    def slope_mean(self) -> _FloatArray: ...
    @property
    def observation_mean(self) -> _FloatArray: ...
    def level_quantile(self, probability: float) -> _FloatArray: ...
    def slope_quantile(self, probability: float) -> _FloatArray: ...
    def observation_quantile(self, probability: float) -> _FloatArray: ...
    def level_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def slope_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    @property
    def uncertainty_kind(self) -> str: ...
    @property
    def interval_kind(self) -> str: ...
    def __repr__(self) -> str: ...

class BoundModel:
    @property
    def id(self) -> str: ...
    @property
    def n_obs(self) -> int: ...
    def __enter__(self) -> BoundModel: ...
    def __exit__(self, _exc_type: Any, _exc_value: Any, _traceback: Any) -> bool: ...

class CompiledModel:
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(text: str) -> CompiledModel: ...
    def log_density(self, data: _Data | BoundModel, position: ArrayLike) -> tuple[float, _FloatArray]: ...
    @property
    def dimensions(self) -> dict[str, str]: ...
    @property
    def param_names(self) -> list[str]: ...
    @property
    def required_keys(self) -> list[str]: ...
    @property
    def structure_id(self) -> int: ...
    def bind(
        self,
        data: _Data,
        id: str = "0",
        strict: bool = True,
        check_finite: bool = True,
    ) -> BoundModel: ...
    def sample(
        self,
        data: _Data | BoundModel,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        seed: int = 42,
        threads: int = 0,
        step_size: float = 0.0,
        target_accept: float = 0.8,
        sampler: Literal["nuts", "hmc"] = "nuts",
        max_tree_depth: int = 10,
        num_leapfrog_steps: int = 15,
        show_progress: bool = True,
        init: ArrayLike | None = None,
    ) -> FitResult: ...
    def sample_iter(self, datasets: Any, **options: Any) -> Any: ...
    def sample_batch(
        self,
        datasets: Sequence[_Data | BoundModel],
        ids: Sequence[str] | None = None,
        shared: _Data | None = None,
        chains: int = 1,
        draws: int = 500,
        warmup: int = 300,
        seed: int = 42,
        sampler: Literal["nuts", "hmc"] = "nuts",
        step_size: float = 0.0,
        target_accept: float = 0.8,
        max_tree_depth: int = 8,
        num_leapfrog_steps: int = 15,
        show_progress: bool = True,
        threads: int = 1,
        chunk_size: int = 64,
        errors: Literal["raise", "collect"] = "raise",
        seed_policy: Literal["cell_id_v1", "position_v0"] = "cell_id_v1",
        init: dict[str, ArrayLike] | None = None,
    ) -> BatchFit: ...
    def __enter__(self) -> CompiledModel: ...
    def __exit__(self, _exc_type: Any, _exc_value: Any, _traceback: Any) -> bool: ...
    def __repr__(self) -> str: ...

class DirichletMultinomialRunoff:
    def __init__(self, alpha: ArrayLike, *, total_shape: float = 2.0, total_rate: float = 0.1) -> None: ...
    def fit(
        self,
        counts: _FloatArray,
        origins: Sequence[int],
        valuation: int,
        totals: Sequence[int | None] | None = None,
        *,
        draws: int = 1000,
        warmup: int = 500,
        chains: int = 4,
        seed: int = 42,
    ) -> RunoffFit: ...

class DynamicGLMFit:
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> DynamicGLMFit: ...
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def groups(self) -> int: ...
    @property
    def observed_count(self) -> int: ...
    @property
    def param_names(self) -> list[str]: ...
    def get_samples_2d(self) -> dict[str, _FloatArray]: ...
    def get_samples(self) -> dict[str, _FloatArray]: ...
    def state_samples(self, component: int = 0) -> _FloatArray: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    def summary(self) -> str: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    def forecast(
        self,
        steps: int,
        *,
        exog: ArrayLike | None = None,
        exposure: ArrayLike | None = None,
        seed: int = 43,
    ) -> DynamicGLMForecast: ...
    def to_arviz(self) -> Any: ...

class DynamicGLMForecast:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def groups(self) -> int: ...
    @property
    def steps(self) -> int: ...
    @property
    def mean(self) -> _FloatArray: ...
    @property
    def observation_mean(self) -> _FloatArray: ...
    def interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def mean_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    @property
    def interval_kind(self) -> str: ...
    @property
    def mean_samples(self) -> _FloatArray: ...
    @property
    def observation_samples(self) -> _FloatArray: ...
    @property
    def occurrence_samples(self) -> _FloatArray | None: ...
    @property
    def positive_mean_samples(self) -> _FloatArray | None: ...
    @property
    def aggregate_observation_samples(self) -> _FloatArray: ...
    @property
    def uncertainty_kind(self) -> str: ...

class Expr:
    def __mul__(self, other: _ExpressionLike) -> Expr: ...
    def __add__(self, other: _ExpressionLike) -> Expr: ...
    def __radd__(self, other: _ExpressionLike) -> Expr: ...
    def __sub__(self, other: _ExpressionLike) -> Expr: ...
    def __rsub__(self, other: _ExpressionLike) -> Expr: ...
    def __truediv__(self, other: _ExpressionLike) -> Expr: ...
    def __rtruediv__(self, other: _ExpressionLike) -> Expr: ...
    def __rmul__(self, other: _ExpressionLike) -> Expr: ...
    def __pow__(self, other: _ExpressionLike, modulo: None = None) -> Expr: ...
    def __rpow__(self, other: _ExpressionLike, modulo: None = None) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def exp(self) -> Expr: ...
    def log(self) -> Expr: ...
    def sqrt(self) -> Expr: ...
    def sigmoid(self) -> Expr: ...
    def tanh(self) -> Expr: ...
    def softplus(self) -> Expr: ...
    def sin(self) -> Expr: ...
    def cos(self) -> Expr: ...
    def sum(self) -> Expr: ...

class FitResult:
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(text: str) -> FitResult: ...
    @property
    def model(self) -> CompiledModel: ...
    def get_samples(self) -> dict[str, _FloatArray]: ...
    def get_samples_2d(self) -> dict[str, _FloatArray]: ...
    def mean(self) -> dict[str, float]: ...
    def std(self) -> dict[str, float]: ...
    def accept_rates(self) -> list[float]: ...
    def summary(self) -> str: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    def transition_diagnostics(self) -> dict[str, Any]: ...
    def step_sizes(self) -> list[float]: ...
    def divergences(self) -> list[int]: ...
    def predict(
        self,
        data: _Data | None = None,
        seed: int = 42,
        expected: bool = False,
        sizes: dict[str, int] | None = None,
    ) -> dict[str, _FloatArray]: ...
    def deterministics(
        self,
        data: _Data | None = None,
        sizes: dict[str, int] | None = None,
    ) -> dict[str, _FloatArray]: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def posterior_predictive(
        self,
        n_samples: int | None = None,
        seed: int = 42,
        data: _Data | None = None,
        expected: bool = False,
        sizes: dict[str, int] | None = None,
    ) -> dict[str, _FloatArray]: ...
    def log_likelihood(self) -> dict[str, _FloatArray]: ...
    def to_arviz(
        self,
        include_ppc: bool = False,
        ppc_samples: int | None = None,
        ppc_seed: int = 42,
        include_log_likelihood: bool = True,
    ) -> Any: ...
    def __repr__(self) -> str: ...

class ForecastBatchFit:
    @property
    def ids(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, id: str) -> _ForecastFit: ...
    @property
    def results(self) -> list[_ForecastFit | None]: ...
    @property
    def errors(self) -> dict[str, str]: ...
    def diagnostics(self) -> dict[str, list[_Diagnostic]]: ...
    def forecast(
        self,
        steps: int,
        *,
        exog: Sequence[ArrayLike | None] | None = None,
        seed: int = 43,
        threads: int = 1,
        chunk_size: int = 64,
        errors: Literal["raise", "collect"] = "raise",
    ) -> ForecastBatchForecast: ...

class ForecastBatchForecast:
    @property
    def ids(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, id: str) -> _ForecastOutput: ...
    @property
    def results(self) -> list[_ForecastOutput | None]: ...
    @property
    def errors(self) -> dict[str, str]: ...

class ForecastResult:
    @property
    def state_means(self) -> _FloatArray: ...
    @property
    def state_covariances(self) -> _FloatArray: ...
    @property
    def observation_means(self) -> _FloatArray: ...
    @property
    def observation_variances(self) -> _FloatArray: ...
    @property
    def observation_covariance(self) -> _FloatArray: ...
    @property
    def cumulative_observation_means(self) -> _FloatArray: ...
    @property
    def cumulative_observation_variances(self) -> _FloatArray: ...
    def interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    def cumulative_interval(self, level: float = 0.95) -> tuple[_FloatArray, _FloatArray]: ...
    @property
    def uncertainty_kind(self) -> str: ...

class GaussianCoefficientPrior:
    def __init__(self, mean: _FloatArray, covariance: _FloatArray) -> None: ...
    @property
    def mean(self) -> _FloatArray: ...
    @property
    def covariance(self) -> _FloatArray: ...

class InverseGammaPrior:
    def __init__(self, shape: float, scale: float) -> None: ...
    @property
    def shape(self) -> float: ...
    @property
    def scale(self) -> float: ...
    def __repr__(self) -> str: ...

class KalmanFilterResult:
    @property
    def log_likelihood(self) -> dict[str, _FloatArray]: ...
    @property
    def predicted_means(self) -> _FloatArray: ...
    @property
    def predicted_covariances(self) -> _FloatArray: ...
    @property
    def filtered_means(self) -> _FloatArray: ...
    @property
    def filtered_covariances(self) -> _FloatArray: ...

class KalmanSmootherResult:
    @property
    def log_likelihood(self) -> dict[str, _FloatArray]: ...
    @property
    def filtered_means(self) -> _FloatArray: ...
    @property
    def filtered_covariances(self) -> _FloatArray: ...
    @property
    def smoothed_means(self) -> _FloatArray: ...
    @property
    def smoothed_covariances(self) -> _FloatArray: ...

class LinearGaussianStateSpace:
    def __init__(
        self,
        transition: _FloatArray,
        observation: _FloatArray,
        process_covariance: _FloatArray,
        observation_variance: float,
        initial_mean: _FloatArray,
        initial_covariance: _FloatArray,
    ) -> None: ...
    @staticmethod
    def local_level(
        process_variance: float,
        observation_variance: float,
        initial_mean: float = 0.0,
        initial_variance: float = 1.0,
    ) -> LinearGaussianStateSpace: ...
    @staticmethod
    def local_linear_trend(
        level_variance: float,
        trend_variance: float,
        observation_variance: float,
        initial_level: float = 0.0,
        initial_trend: float = 0.0,
        initial_level_variance: float = 1.0,
        initial_trend_variance: float = 1.0,
    ) -> LinearGaussianStateSpace: ...
    @staticmethod
    def seasonal_local_level(
        period: int,
        level_variance: float,
        seasonal_variance: float,
        observation_variance: float,
        initial_level: float = 0.0,
        initial_seasonal_effects: ArrayLike | None = None,
        initial_level_variance: float = 1.0,
        initial_seasonal_variance: float = 1.0,
    ) -> LinearGaussianStateSpace: ...
    @staticmethod
    def stationary_ar1(
        coefficient: float,
        process_variance: float,
        observation_variance: float,
    ) -> LinearGaussianStateSpace: ...
    @property
    def dimension(self) -> int: ...
    def with_observation_rows(self, observation_rows: _FloatArray) -> LinearGaussianStateSpace: ...
    def filter(self, observations: _FloatArray) -> KalmanFilterResult: ...
    def smooth(self, observations: _FloatArray) -> KalmanSmootherResult: ...
    def forecast(
        self,
        observations: _FloatArray,
        steps: int,
        *,
        future_observation_rows: _FloatArray | None = None,
    ) -> ForecastResult: ...

class ModelBuilder:
    def __init__(self, data: _Data | None = None, dims: dict[str, str] | None = None) -> None: ...
    def data(self, name: str, dim: str | None = None) -> Expr: ...
    def potential(self, name: str, expression: _ExpressionLike) -> None: ...
    def deterministic(self, name: str, expression: _ExpressionLike) -> Expr: ...
    def __enter__(self) -> ModelBuilder: ...
    def __exit__(self, _exc_type: Any, _exc_value: Any, _traceback: Any) -> bool: ...
    def normal_prior(self, name: str, mu: float | ParamRef, sigma: float | ParamRef) -> ParamRef: ...
    def half_normal_prior(self, name: str, sigma: float | ParamRef) -> ParamRef: ...
    def exponential_prior(self, name: str, rate: float | ParamRef) -> ParamRef: ...
    def log_normal_prior(self, name: str, mu: float | ParamRef, sigma: float | ParamRef) -> ParamRef: ...
    def student_t_prior(self, name: str, nu: float, mu: float = 0.0, sigma: float = 1.0) -> ParamRef: ...
    def uniform_prior(self, name: str, lower: float = 0.0, upper: float = 1.0) -> ParamRef: ...
    def bernoulli_prior(self, name: str, p: float = 0.5) -> ParamRef: ...
    def poisson_prior(self, name: str, lam: float) -> ParamRef: ...
    def gamma_prior(self, name: str, alpha: float, beta: float) -> ParamRef: ...
    def beta_prior(self, name: str, alpha: float, beta: float) -> ParamRef: ...
    def vector_normal_prior(
        self,
        name: str,
        n: int,
        mu: float = 0.0,
        sigma: float = 1.0,
    ) -> VectorParamRef: ...
    def normal_likelihood(
        self,
        name: str,
        mu_expr: _ExpressionLike,
        sigma: float | ParamRef,
        observed_key: str,
    ) -> None: ...
    def bernoulli_logit_likelihood(
        self,
        name: str,
        eta_expr: _ExpressionLike,
        observed_key: str,
    ) -> None: ...
    def poisson_log_likelihood(self, name: str, eta_expr: _ExpressionLike, observed_key: str) -> None: ...
    def exponential_likelihood(self, name: str, eta_expr: _ExpressionLike, observed_key: str) -> None: ...
    def log_normal_likelihood(
        self,
        name: str,
        mu_expr: _ExpressionLike,
        sigma: float | ParamRef,
        observed_key: str,
    ) -> None: ...
    def negative_binomial_likelihood(
        self,
        name: str,
        eta_expr: _ExpressionLike,
        alpha: float | ParamRef,
        observed_key: str,
    ) -> None: ...
    def build(self) -> ModelSpec: ...
    def compile(self) -> CompiledModel: ...

class ModelSpec:
    ...

class NormalInverseGammaPrior:
    def __init__(
        self,
        coefficient_mean: _FloatArray,
        coefficient_precision: _FloatArray,
        variance_shape: float,
        variance_scale: float,
    ) -> None: ...
    @property
    def coefficient_mean(self) -> _FloatArray: ...
    @property
    def coefficient_precision(self) -> _FloatArray: ...
    @property
    def variance_shape(self) -> float: ...
    @property
    def variance_scale(self) -> float: ...
    @property
    def coefficient_count(self) -> int: ...
    def __repr__(self) -> str: ...

class ParamRef:
    def __mul__(self, other: _ExpressionLike | str) -> Expr: ...
    def __matmul__(self, data_key: str) -> Expr: ...
    def __add__(self, other: _ExpressionLike) -> Expr: ...
    def __radd__(self, other: _ExpressionLike) -> Expr: ...
    def __sub__(self, other: _ExpressionLike) -> Expr: ...
    def __rsub__(self, other: _ExpressionLike) -> Expr: ...
    def __truediv__(self, other: _ExpressionLike) -> Expr: ...
    def __rtruediv__(self, other: _ExpressionLike) -> Expr: ...
    def __rmul__(self, other: _ExpressionLike | str) -> Expr: ...
    def __pow__(self, other: _ExpressionLike, modulo: None = None) -> Expr: ...
    def __rpow__(self, other: _ExpressionLike, modulo: None = None) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def exp(self) -> Expr: ...
    def log(self) -> Expr: ...
    def sqrt(self) -> Expr: ...
    def sigmoid(self) -> Expr: ...
    def tanh(self) -> Expr: ...
    def softplus(self) -> Expr: ...
    def sin(self) -> Expr: ...
    def cos(self) -> Expr: ...
    def sum(self) -> Expr: ...

class RunoffFit:
    def diagnostics(self) -> list[_Diagnostic]: ...
    def summary(self) -> str: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    @property
    def allocation_samples(self) -> _UIntArray: ...
    @property
    def lag_probability_samples(self) -> _FloatArray: ...
    @property
    def ultimate_samples(self) -> _UIntArray: ...
    @property
    def intensity_samples(self) -> _FloatArray: ...
    @property
    def tail_samples(self) -> _UIntArray: ...
    def calendar_samples(self, steps: int) -> _UIntArray: ...
    @property
    def observed_mask(self) -> _BoolArray: ...
    @property
    def origins(self) -> list[int]: ...
    @property
    def valuation(self) -> int: ...
    @property
    def sampler(self) -> str: ...

class StructuralComponent:
    @staticmethod
    def level(
        name: str,
        innovation: VarianceParameter,
        initial_mean: float,
        initial_variance: float,
    ) -> StructuralComponent: ...
    @staticmethod
    def trend(
        name: str,
        level_innovation: VarianceParameter,
        slope_innovation: VarianceParameter,
        initial_mean: ArrayLike,
        initial_covariance: ArrayLike,
        damping: float = 1.0,
    ) -> StructuralComponent: ...
    @staticmethod
    def seasonal(
        name: str,
        period: float,
        harmonics: int,
        innovation: VarianceParameter,
        initial_variance: float,
    ) -> StructuralComponent: ...
    @staticmethod
    def regression(
        name: str,
        initial_mean: ArrayLike,
        initial_covariance: ArrayLike,
        innovations: Sequence[VarianceParameter] | None = None,
    ) -> StructuralComponent: ...
    @staticmethod
    def ar(
        name: str,
        coefficients: ArrayLike,
        innovation: VarianceParameter,
        initial_mean: ArrayLike,
        initial_covariance: ArrayLike,
    ) -> StructuralComponent: ...
    @property
    def name(self) -> str: ...

class StructuralFit:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def param_names(self) -> list[str]: ...
    def get_samples_2d(self) -> dict[str, _FloatArray]: ...
    def get_samples(self) -> dict[str, _FloatArray]: ...
    def diagnostics(self) -> list[_Diagnostic]: ...
    def summary(self) -> str: ...
    @property
    def sampler_stats(self) -> dict[str, Any]: ...
    @property
    def model(self) -> StructuralModel: ...
    @property
    def component_names(self) -> list[str]: ...
    @property
    def variance_names(self) -> list[str]: ...
    @property
    def variance_draws(self) -> _FloatArray: ...
    @property
    def terminal_states(self) -> _FloatArray: ...
    @property
    def states(self) -> _FloatArray: ...
    @property
    def historical_components(self) -> _FloatArray: ...
    def forecast(
        self,
        steps: int,
        *,
        exog: ArrayLike | None = None,
        seed: int = 43,
    ) -> StructuralForecast: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(value: str) -> StructuralFit: ...

class StructuralForecast:
    @property
    def chains(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def steps(self) -> int: ...
    @property
    def mean_samples(self) -> _FloatArray: ...
    @property
    def observation_samples(self) -> _FloatArray: ...
    @property
    def uncertainty_kind(self) -> str: ...
    @property
    def component_names(self) -> list[str]: ...
    @property
    def state_paths(self) -> _FloatArray: ...
    @property
    def component_paths(self) -> _FloatArray: ...
    @property
    def mean_paths(self) -> _FloatArray: ...
    @property
    def observation_paths(self) -> _FloatArray: ...
    @property
    def cumulative_observation_paths(self) -> _FloatArray: ...

class StructuralModel:
    def __init__(
        self,
        components: Sequence[StructuralComponent],
        observation_variance: VarianceParameter,
        student_df: float | None = None,
    ) -> None: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(value: str) -> StructuralModel: ...
    @property
    def component_names(self) -> list[str]: ...
    @property
    def dimension(self) -> int: ...
    def fit(
        self,
        observations: ArrayLike,
        *,
        exog: ArrayLike | None = None,
        chains: int = 4,
        draws: int = 1000,
        warmup: int = 500,
        thin: int = 1,
        seed: int = 42,
        store_states: bool = False,
    ) -> StructuralFit: ...
    def prior_predict(
        self,
        steps: int,
        *,
        exog: ArrayLike | None = None,
        draws: int = 1000,
        seed: int = 43,
    ) -> StructuralForecast: ...

class VarianceParameter:
    @staticmethod
    def fixed(value: float) -> VarianceParameter: ...
    @staticmethod
    def inverse_gamma(shape: float, scale: float) -> VarianceParameter: ...

class VectorParamRef:
    def __getitem__(self, data_key: str) -> Expr: ...
    def __matmul__(self, data_key: str) -> Expr: ...

def sample(
    model_spec: ModelSpec,
    data: _Data | None = None,
    chains: int = 4,
    draws: int = 1000,
    warmup: int = 500,
    seed: int = 42,
    threads: int = 0,
    step_size: float = 0.0,
    target_accept: float = 0.8,
    sampler: Literal["nuts", "hmc"] = "nuts",
    max_tree_depth: int = 10,
    num_leapfrog_steps: int = 15,
    show_progress: bool = True,
    init: ArrayLike | None = None,
) -> FitResult: ...

def batch_sample(
    models: Sequence[tuple[ModelSpec, _Data]],
    chains: int = 1,
    draws: int = 500,
    warmup: int = 300,
    seed: int = 42,
    sampler: Literal["nuts", "hmc"] = "nuts",
    step_size: float = 0.0,
    target_accept: float = 0.8,
    max_tree_depth: int = 8,
    num_leapfrog_steps: int = 15,
    show_progress: bool = True,
) -> list[BatchResult]: ...

def sample_prior_predictive(
    model_spec: ModelSpec,
    data: _Data | None = None,
    n_samples: int = 500,
    seed: int = 42,
) -> dict[str, _FloatArray]: ...

def fourier_design(count: int, period: int, harmonics: int, start: int = 0) -> _FloatArray: ...

def hurdle_lognormal_logp(
    y: float,
    payment_probability: float,
    log_level: float,
    log_variance: float,
) -> float: ...

def forecast_cell_seed(seed: int, cell_id: str, domain: Literal["fit", "forecast"] = "fit") -> int: ...

def BayesianDynamicPoisson(
    *,
    initial_mean: float = 0.0,
    occurrence_initial_mean: float = 0.0,
    coefficient_sd: float = 1.0,
    group_sd: float = 0.5,
    process_sd: float = 0.1,
    shared_process_sd: float = 0.0,
    observation_sd: float = 1.0,
    dispersion: float = 5.0,
) -> BayesianDynamicGLM: ...

def BayesianDynamicNegativeBinomial(
    *,
    initial_mean: float = 0.0,
    occurrence_initial_mean: float = 0.0,
    coefficient_sd: float = 1.0,
    group_sd: float = 0.5,
    process_sd: float = 0.1,
    shared_process_sd: float = 0.0,
    observation_sd: float = 1.0,
    dispersion: float = 5.0,
) -> BayesianDynamicGLM: ...

def BayesianDynamicHurdleLogNormal(
    *,
    initial_mean: float = 0.0,
    occurrence_initial_mean: float = 0.0,
    coefficient_sd: float = 1.0,
    group_sd: float = 0.5,
    process_sd: float = 0.1,
    shared_process_sd: float = 0.0,
    observation_sd: float = 1.0,
    dispersion: float = 5.0,
) -> BayesianDynamicGLM: ...

def BayesianHierarchicalDynamicRegression(
    *,
    initial_mean: float = 0.0,
    occurrence_initial_mean: float = 0.0,
    coefficient_sd: float = 1.0,
    group_sd: float = 0.5,
    process_sd: float = 0.1,
    shared_process_sd: float = 0.0,
    observation_sd: float = 1.0,
    dispersion: float = 5.0,
) -> BayesianDynamicGLM: ...

BayesianAR = BayesianAutoRegression

_ForecastPreset = BayesianLocalLevel | BayesianLocalLinearTrend | BayesianSeasonalLocalLevel | BayesianAutoRegression | BayesianHurdleLogNormal
_ForecastFit = BayesianLocalLevelFit | BayesianLocalLinearTrendFit | BayesianSeasonalLocalLevelFit | BayesianARFit | BayesianHurdleLogNormalFit | BayesianRegressionFit
_ForecastOutput = BayesianForecastResult | BayesianTrendForecast | BayesianSeasonalForecast | BayesianARForecast | BayesianHurdleLogNormalForecast | BayesianRegressionForecast
