#!/usr/bin/env python3
"""Generate documentation pages from the example scripts, with real output.

`examples/*.py` is the single source of truth for example code. This script
executes an example and writes a page that interleaves each block of code with
the output that block actually produced, so a reader sees the program and its
results together without a notebook in the repository.

    python scripts/build_example_docs.py            # regenerate the pages
    python scripts/build_example_docs.py --check    # fail if a page is stale

Cell format
-----------
An example opts in by using the "percent format" cell convention. The file
stays an ordinary runnable script -- `python examples/simple_example.py` and
`scripts/run_examples.py` are unaffected -- and this script splits it on the
markers:

    # %% Heading for a code cell
    # %% [markdown]

A `# %%` line starts a code cell; any text after the marker becomes an `##`
heading on the page. A `# %% [markdown]` cell is prose: its `#`-prefixed lines
are stripped of the comment marker and emitted as markdown, and nothing in it
runs. Code before the first marker (the imports) is emitted without a heading.
The module docstring becomes the page title and introduction.

Cells execute in order in one shared namespace, exactly as the script does when
run normally, and each cell's standard output is captured and shown beneath it.
Progress bars go to standard error, which is not captured, so the timing line
the sampler prints while working never reaches a page.

Why the pages are committed
---------------------------
They are committed and CI fails on drift, rather than being generated only at
deploy time. Generating at deploy keeps the published site fresh but leaves a
stale copy in the repository, which is exactly how `docs/examples/hierarchical.md`
came to advertise 128 divergent transitions for a model that now has none.
Committing the pages means the numbers are reviewed in the pull request that
changes them.

That only works if regeneration is reproducible, so a documented example must be
seeded, must not depend on wall-clock time or the machine, and must not need a
package outside this project's dependencies. Anything genuinely variable is
normalised by `NORMALISERS` below. A normaliser that stops matching is an error:
a silently dead normaliser means the line it protected has been renamed and the
drift check is about to start failing at random.

Regenerated output can still change when the sampler's arithmetic changes --
a new Rust toolchain that vectorises a reduction differently will move the last
digits. That is a true signal, not noise: the documented numbers really did
change. Rerun this script and commit the result.
"""
from __future__ import annotations

import argparse
import ast
import contextlib
import difflib
import io
import re
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_examples import documented  # noqa: E402  (same directory, same manifest)

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
PAGES = ROOT / "docs" / "examples"

CELL_MARKER = re.compile(r"^# %%(?:\s+(.*))?$")
MARKDOWN_CELL = "[markdown]"

# Lines that are correct but differ between runs, with the reason each one is
# unreproducible. Everything else must be identical run to run; if a new example
# prints something variable, normalise it here rather than loosening the check.
NORMALISERS: list[tuple[str, re.Pattern[str], str]] = [
    (
        "wall-clock build time",
        re.compile(r"(?m)^(Model built in )[\d.]+s$"),
        r"\g<1><elapsed>s",
    ),
    (
        "wall-clock sampling time",
        re.compile(r"(?m)^(Elapsed\s*:\s*)[\d.]+s$"),
        r"\g<1><elapsed>s",
    ),
    (
        "iterations per second, derived from wall-clock time",
        re.compile(r"(?m)^(Iters/s\s*:\s*)[\d.]+$"),
        r"\g<1><rate>",
    ),
]

BANNER = (
    "<!-- Generated by scripts/build_example_docs.py from {source}. Do not edit\n"
    "     this file: edit the example and regenerate. CI fails on drift. -->\n"
)


class ExampleError(RuntimeError):
    """An example failed while its page was being generated."""


def page_path(script: Path) -> Path:
    """docs/examples/<script name with hyphens>.md, and nothing cleverer."""
    return PAGES / (script.stem.replace("_", "-") + ".md")


def split_cells(source: str, script: Path) -> tuple[str, list[tuple[str, str, str]]]:
    """Return (module docstring, cells), each cell (kind, heading, body).

    `kind` is "code" or "markdown". Cell bodies keep their original line numbers
    so a traceback from a failing example points at the real file.
    """
    lines = source.splitlines()

    module = ast.parse(source, filename=str(script))
    docstring = ast.get_docstring(module) or ""
    if not docstring:
        raise ExampleError(f"{script.name}: needs a module docstring for the page intro")
    start = module.body[0].end_lineno  # first statement is the docstring

    cells: list[tuple[str, str, str]] = []
    current_kind, current_heading, current_start = "code", "", start
    body: list[str] = []

    def flush() -> None:
        text = "\n".join(body)
        if text.strip():
            padded = "\n" * current_start + text
            cells.append((current_kind, current_heading, padded))

    for index in range(start, len(lines)):
        match = CELL_MARKER.match(lines[index])
        if not match:
            body.append(lines[index])
            continue
        flush()
        label = (match.group(1) or "").strip()
        if label.startswith(MARKDOWN_CELL):
            current_kind = "markdown"
            current_heading = label[len(MARKDOWN_CELL) :].strip()
        else:
            current_kind = "code"
            current_heading = label
        current_start, body = index + 1, []
    flush()
    return docstring, cells


def render_markdown_cell(body: str) -> str:
    """Strip the leading comment marker from a prose cell."""
    out = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            out.append("")
        elif stripped.startswith("# "):
            out.append(stripped[2:])
        elif stripped == "#":
            out.append("")
        else:
            raise ExampleError(f"markdown cell has a non-comment line: {line!r}")
    return "\n".join(out).strip("\n")


def normalise(text: str, fired: set[str]) -> str:
    for name, pattern, replacement in NORMALISERS:
        text, count = pattern.subn(replacement, text)
        if count:
            fired.add(name)
    return text


def build_page(script: Path, fired: set[str]) -> str:
    source = script.read_text(encoding="utf-8")
    docstring, cells = split_cells(source, script)
    if not any(kind == "code" for kind, _, _ in cells):
        raise ExampleError(f"{script.name}: no cells to run")

    title, _, intro = docstring.partition("\n")
    parts = [BANNER.format(source=f"examples/{script.name}"), f"# {title.strip()}\n"]
    if intro.strip():
        parts.append(textwrap.dedent(intro).strip("\n") + "\n")

    # Run exactly as `python examples/<name>.py` does: the script's directory on
    # sys.path so sibling-module imports resolve, __name__ == "__main__" so a
    # main guard fires, and the repository root as the working directory.
    namespace = {"__name__": "__main__", "__file__": str(script)}
    sys.path.insert(0, str(EXAMPLES))
    try:
        for kind, heading, body in cells:
            if heading:
                parts.append(f"## {heading}\n")
            if kind == "markdown":
                parts.append(render_markdown_cell(body) + "\n")
                continue
            buffer = io.StringIO()
            try:
                with contextlib.redirect_stdout(buffer):
                    exec(compile(body, str(script), "exec"), namespace)  # noqa: S102
            except BaseException as error:  # noqa: BLE001 - reported, not swallowed
                raise ExampleError(
                    f"{script.name} failed in cell {heading or '(imports)'!r}: "
                    f"{type(error).__name__}: {error}"
                ) from error
            parts.append("```python\n" + body.strip("\n") + "\n```\n")
            output = normalise(buffer.getvalue(), fired).rstrip("\n")
            if output:
                parts.append("```text\n" + output + "\n```\n")
    finally:
        sys.path.remove(str(EXAMPLES))

    return "\n".join(parts).rstrip("\n") + "\n"


def participating() -> list[Path]:
    """Documented examples that carry cell markers, in page order."""
    listed, _ = documented()
    scripts = []
    for name in sorted(listed):
        script = EXAMPLES / name
        if any(CELL_MARKER.match(line) for line in script.read_text(encoding="utf-8").splitlines()):
            scripts.append(script)
    return scripts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail if a committed page differs",
    )
    args = parser.parse_args()

    scripts = participating()
    if not scripts:
        print("no example carries '# %%' cell markers", file=sys.stderr)
        return 1

    fired: set[str] = set()
    stale: list[str] = []
    for script in scripts:
        target = page_path(script)
        try:
            page = build_page(script, fired)
        except ExampleError as error:
            print(f"FAILED  {script.name}\n  {error}", file=sys.stderr)
            return 1
        existing = target.read_text(encoding="utf-8") if target.exists() else ""
        if args.check:
            if page != existing:
                stale.append(target.relative_to(ROOT).as_posix())
                sys.stderr.writelines(
                    difflib.unified_diff(
                        existing.splitlines(keepends=True),
                        page.splitlines(keepends=True),
                        fromfile=f"committed/{target.name}",
                        tofile=f"regenerated/{target.name}",
                    )
                )
            print(f"{'STALE' if page != existing else '   ok'}  {target.relative_to(ROOT)}")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(page, encoding="utf-8")
            print(f"{'updated' if page != existing else '     ok'}  {target.relative_to(ROOT)}")

    unused = [name for name, _, _ in NORMALISERS if name not in fired]
    if unused:
        print(
            "\nThese NORMALISERS matched nothing, so the variable line each one\n"
            "protected has been renamed or removed. Fix or delete them, or the\n"
            "drift check will start failing at random:\n  "
            + "\n  ".join(unused),
            file=sys.stderr,
        )
        return 1

    if stale:
        print(
            f"\n{len(stale)} page(s) out of date with the examples that produce them:\n  "
            + "\n  ".join(stale)
            + "\n\nRun `python scripts/build_example_docs.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    print(f"\n{len(scripts)} page(s) {'checked' if args.check else 'written'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
