#!/usr/bin/env python3
"""Generate documentation pages from the example scripts, with real output.

`examples/*.py` is the single source of truth for example code. This script
executes an example and writes a page that interleaves each block of code with
the output that block actually produced, so a reader sees the program and its
results together without a notebook in the repository.

    python scripts/build_example_docs.py            # regenerate the pages
    python scripts/build_example_docs.py --check    # fail if a page is stale

Cell format
-----------
An example opts in by using the "percent format" cell convention. The file
stays an ordinary runnable script -- `python examples/simple_example.py` and
`scripts/run_examples.py` are unaffected -- and this script splits it on the
markers:

    # %% Heading for a code cell
    # %% [markdown]

A `# %%` line starts a code cell; any text after the marker becomes an `##`
heading on the page. A `# %% [markdown]` cell is prose: its `#`-prefixed lines
are stripped of the comment marker and emitted as markdown, and nothing in it
runs. Code before the first marker (the imports) is emitted without a heading.
The module docstring becomes the page title and introduction.

Cells execute in order in one shared namespace, as the script does when run
normally, and each cell's standard output is captured and shown beneath it. Each
example gets its own subprocess, so one example cannot leave NumPy's global RNG
or `sys.modules` in a state that changes another example's numbers.

A page shows captured standard output only. The sampler's progress bar goes to
standard error and carries an elapsed time, so putting stderr on a page would
put an unreproducible line on it. That leaves a blind spot -- a warning a cell
starts emitting would change no page -- so whatever a cell writes to stderr
other than the progress bar is echoed to the console instead.

Why the pages are committed
---------------------------
They are committed and CI fails on drift, rather than being generated only at
deploy time. Generating at deploy keeps the published site fresh but leaves a
stale copy in the repository, which is exactly how `docs/examples/hierarchical.md`
came to advertise 128 divergent transitions for a model that now has none.
Committing the pages means the numbers are reviewed in the pull request that
changes them.

That only works if regeneration is reproducible, so a documented example must be
seeded, must not depend on wall-clock time or the machine, and must not need a
package outside this project's dependencies. Anything genuinely variable is
normalised by `NORMALISERS` below. A normaliser that stops matching is an error:
a silently dead normaliser means the line it protected has been renamed and the
drift check is about to start failing at random.

Regenerated output can still change when the sampler's arithmetic changes --
a new Rust toolchain that vectorises a reduction differently will move the last
digits. That is a true signal, not noise: the documented numbers really did
change. Rerun this script and commit the result.
"""
from __future__ import annotations

import argparse
import ast
import contextlib
import difflib
import io
import json
import re
import subprocess
import sys
import tempfile
import textwrap
import tokenize
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_examples import documented  # noqa: E402  (same directory, same manifest)

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
PAGES = ROOT / "docs" / "examples"

CELL_MARKER = re.compile(r"^# %%(?:\s+(.*))?$")
MARKDOWN_CELL = "[markdown]"

# The sampler's progress bar, which carries an elapsed time and so is the one
# thing on stderr that `report_stderr` must not treat as news.
PROGRESS = re.compile(r"^[\r\x1b\[\dA-Za-z; ]*Sampling[ :]")

# Lines that are correct but differ between runs, with the reason each one is
# unreproducible. Everything else must be identical run to run; if a new example
# prints something variable, normalise it here rather than loosening the check.
NORMALISERS: list[tuple[str, re.Pattern[str], str]] = [
    (
        "wall-clock build time",
        re.compile(r"(?m)^(Model built in )[\d.]+s$"),
        r"\g<1><elapsed>s",
    ),
    (
        "wall-clock sampling time",
        re.compile(r"(?m)^(Elapsed\s*:\s*)[\d.]+s$"),
        r"\g<1><elapsed>s",
    ),
    (
        "iterations per second, derived from wall-clock time",
        re.compile(r"(?m)^(Iters/s\s*:\s*)[\d.]+$"),
        r"\g<1><rate>",
    ),
]

BANNER = (
    "<!-- Generated by scripts/build_example_docs.py from {source}. Do not edit\n"
    "     this file: edit the example and regenerate. CI fails on drift. -->\n"
)


class ExampleError(RuntimeError):
    """An example failed while its page was being generated."""


def page_path(script: Path) -> Path:
    """docs/examples/<script name with hyphens>.md, and nothing cleverer."""
    return PAGES / (script.stem.replace("_", "-") + ".md")


def marker_lines(source: str, script: Path) -> dict[int, re.Match[str]]:
    """Map 0-based line number -> cell marker, for real comments only.

    Matching `# %%` textually would cut a triple-quoted string that happens to
    contain such a line into separate cells, turning a valid script into a
    SyntaxError. Tokenizing means only an actual comment token can start a cell.
    """
    found: dict[int, re.Match[str]] = {}
    try:
        tokens = tokenize.generate_tokens(io.StringIO(source).readline)
        for token in tokens:
            if token.type != tokenize.COMMENT or token.start[1] != 0:
                continue
            match = CELL_MARKER.match(token.string)
            if match:
                found[token.start[0] - 1] = match
    except tokenize.TokenError as error:
        raise ExampleError(f"{script.name}: cannot tokenize: {error}") from error
    return found


def split_cells(source: str, script: Path) -> tuple[str, list[tuple[str, str, str]]]:
    """Return (module docstring, cells), each cell (kind, heading, body).

    `kind` is "code" or "markdown". Cell bodies keep their original line numbers
    so a traceback from a failing example points at the real file.
    """
    lines = source.splitlines()

    module = ast.parse(source, filename=str(script))
    docstring = ast.get_docstring(module) or ""
    if not docstring:
        raise ExampleError(f"{script.name}: needs a module docstring for the page intro")
    start = module.body[0].end_lineno  # first statement is the docstring

    markers = marker_lines(source, script)
    cells: list[tuple[str, str, str]] = []
    current_kind, current_heading, current_start = "code", "", start
    body: list[str] = []

    def flush() -> None:
        text = "\n".join(body)
        if text.strip():
            padded = "\n" * current_start + text
            cells.append((current_kind, current_heading, padded))

    for index in range(start, len(lines)):
        match = markers.get(index)
        if match is None:
            body.append(lines[index])
            continue
        flush()
        label = (match.group(1) or "").strip()
        if label.startswith(MARKDOWN_CELL):
            current_kind = "markdown"
            current_heading = label[len(MARKDOWN_CELL) :].strip()
        else:
            current_kind = "code"
            current_heading = label
        current_start, body = index + 1, []
    flush()
    return docstring, cells


def render_markdown_cell(body: str) -> str:
    """Strip the leading comment marker from a prose cell.

    Only leading whitespace is removed. Trailing whitespace is prose: two spaces
    at the end of a line are a Markdown hard break.
    """
    out = []
    for line in body.splitlines():
        stripped = line.lstrip()
        if not stripped.strip():
            out.append("")
        elif stripped.startswith("# "):
            out.append(stripped[2:])
        elif stripped.rstrip() == "#":
            out.append("")
        else:
            raise ExampleError(f"markdown cell has a non-comment line: {line!r}")
    return "\n".join(out).strip("\n")


def report_stderr(script: Path, heading: str, text: str) -> None:
    """Echo anything a cell wrote to stderr that is not the sampler's progress bar.

    Pages show captured stdout only, because the progress bar carries an elapsed
    time that would differ on every run. That leaves a blind spot: a warning a
    cell starts emitting would reach nobody and change no page. Echoing what is
    left after the progress lines are removed puts it in front of whoever runs
    the generator, without putting an unreproducible line on a page.
    """
    leftover = [line for line in text.splitlines() if line.strip() and not PROGRESS.match(line)]
    if leftover:
        where = heading or "(imports)"
        print(f"stderr from {script.name} in cell {where!r}:", file=sys.stderr)
        for line in leftover:
            print(f"  {line}", file=sys.stderr)


def normalise(text: str, fired: set[str]) -> str:
    for name, pattern, replacement in NORMALISERS:
        text, count = pattern.subn(replacement, text)
        if count:
            fired.add(name)
    return text


def build_page(script: Path, fired: set[str]) -> str:
    source = script.read_text(encoding="utf-8")
    docstring, cells = split_cells(source, script)
    if not any(kind == "code" for kind, _, _ in cells):
        raise ExampleError(f"{script.name}: no cells to run")

    title, _, intro = docstring.partition("\n")
    parts = [BANNER.format(source=f"examples/{script.name}"), f"# {title.strip()}\n"]
    if intro.strip():
        parts.append(textwrap.dedent(intro).strip("\n") + "\n")

    # Run as `python examples/<name>.py` does: the script's directory first on
    # sys.path so sibling-module imports resolve, __name__ == "__main__" so a main
    # guard fires, its own __doc__ and argv, and the repository root as the working
    # directory, which `render_one` sets for this whole process. `render_one` also
    # gives the process to one example, so NumPy's global RNG and sys.modules start
    # clean rather than carrying another example's state.
    namespace = {"__name__": "__main__", "__file__": str(script), "__doc__": docstring}
    sys.path.insert(0, str(EXAMPLES))
    sys.argv = [str(script)]
    for kind, heading, body in cells:
        if heading:
            parts.append(f"## {heading}\n")
        if kind == "markdown":
            parts.append(render_markdown_cell(body) + "\n")
            continue
        out, err = io.StringIO(), io.StringIO()
        try:
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                # dont_inherit, or the cell would run under this file's
                # `from __future__ import annotations` and behave unlike the script.
                exec(compile(body, str(script), "exec", dont_inherit=True), namespace)  # noqa: S102
        except BaseException as error:  # noqa: BLE001 - reported, not swallowed
            sys.stderr.write(err.getvalue())
            # Cell bodies are padded to their real line offsets, so the frames
            # below point at examples/<name>.py, not at an anonymous cell.
            raise ExampleError(
                f"{script.name} failed in cell {heading or '(imports)'!r}\n"
                + "".join(traceback.format_exception(error)).rstrip()
            ) from error
        report_stderr(script, heading, err.getvalue())
        parts.append("```python\n" + body.strip("\n") + "\n```\n")
        output = normalise(out.getvalue(), fired).rstrip("\n")
        if output:
            parts.append("```text\n" + output + "\n```\n")

    return "\n".join(parts).rstrip("\n") + "\n"


def render_one(script: Path) -> tuple[str, set[str]]:
    """Build one page in a subprocess, and return it with the normalisers it used.

    One process per example, rather than all of them in this one. Examples share
    NumPy's global RNG and `sys.modules`, so running them together would make a
    page's numbers depend on which pages ran before it. The drift check would
    still be reproducible -- the order is fixed -- but adding an example could
    silently change an unrelated page, and the failure would be baffling.
    """
    with tempfile.TemporaryDirectory() as scratch:
        result = Path(scratch) / "page.json"
        done = subprocess.run(  # noqa: S603 - fixed argv, no shell
            [sys.executable, str(Path(__file__).resolve()), "--render", str(script), str(result)],
            cwd=ROOT,
        )
        if done.returncode != 0:
            # The child already wrote the traceback to the shared stderr.
            raise ExampleError(f"{script.name}: rendering exited {done.returncode}")
        payload = json.loads(result.read_text(encoding="utf-8"))
    return payload["page"], set(payload["fired"])


def participating() -> list[Path]:
    """Documented examples that carry cell markers, in page order.

    Opting in is adding `# %%` markers to an example that `examples/README.md`
    already lists. Nothing else has to be registered, and an example without
    markers simply has no page.
    """
    listed, _ = documented()
    scripts = []
    for name in sorted(listed):
        script = EXAMPLES / name
        if not script.exists():
            continue  # scripts/run_examples.py is what reports a broken manifest
        if any(CELL_MARKER.match(line) for line in script.read_text(encoding="utf-8").splitlines()):
            scripts.append(script)
    return scripts


# Pages in docs/examples/ that are written by hand rather than generated. Empty
# on purpose: every page there comes from an example. A hand-written page must be
# named here, which is also the record of why it is an exception.
HAND_WRITTEN: set[str] = set()


def orphans(expected: set[Path]) -> list[str]:
    """Pages in docs/examples/ that no example produces.

    Deleting an example, renaming it, or dropping its cell markers would
    otherwise leave its page behind, committed and checked by nothing -- stale
    output by another route. Every file in the directory has to be accounted for,
    rather than only those still carrying a generated banner, because a banner is
    one line an editor can remove.
    """
    return [
        page.relative_to(ROOT).as_posix()
        for page in sorted(PAGES.glob("*.md"))
        if page not in expected and page.name not in HAND_WRITTEN
    ]


def main() -> int:
    # __doc__ in full is several screens and argparse reflows it into a wall, so
    # the help shows its first paragraph and points at the file for the rest.
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0] + "\n\nSee this file's docstring for the "
        "cell format and why the pages are committed.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail if a committed page differs",
    )
    parser.add_argument(
        "--render",
        nargs=2,
        metavar=("EXAMPLE", "RESULT"),
        help=argparse.SUPPRESS,  # internal: how render_one runs one example
    )
    args = parser.parse_args()

    if args.render:
        script, result = Path(args.render[0]), Path(args.render[1])
        fired: set[str] = set()
        try:
            page = build_page(script, fired)
        except ExampleError as error:
            print(f"FAILED  {script.name}\n  {error}", file=sys.stderr)
            return 1
        result.write_text(json.dumps({"page": page, "fired": sorted(fired)}), encoding="utf-8")
        return 0

    scripts = participating()
    if not scripts:
        print("no example carries '# %%' cell markers", file=sys.stderr)
        return 1

    fired = set()
    stale: list[str] = []
    for script in scripts:
        target = page_path(script)
        try:
            page, used = render_one(script)
        except ExampleError as error:
            print(f"FAILED  {script.name}: {error}", file=sys.stderr)
            return 1
        fired |= used
        existing = target.read_text(encoding="utf-8") if target.exists() else ""
        if args.check:
            if page != existing:
                stale.append(target.relative_to(ROOT).as_posix())
                sys.stderr.writelines(
                    difflib.unified_diff(
                        existing.splitlines(keepends=True),
                        page.splitlines(keepends=True),
                        fromfile=f"committed/{target.name}",
                        tofile=f"regenerated/{target.name}",
                    )
                )
            print(f"{'STALE' if page != existing else '   ok'}  {target.relative_to(ROOT)}")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(page, encoding="utf-8")
            print(f"{'updated' if page != existing else '     ok'}  {target.relative_to(ROOT)}")

    left_over = orphans({page_path(script) for script in scripts})
    if left_over:
        print(
            "\nNo example produces these pages. Delete them, restore the example\n"
            "that made them, or, if one really is hand-written, name it in\n"
            "HAND_WRITTEN in this script:\n  "
            + "\n  ".join(left_over),
            file=sys.stderr,
        )
        return 1

    unused = [name for name, _, _ in NORMALISERS if name not in fired]
    if unused:
        print(
            "\nThese NORMALISERS matched nothing, so the variable line each one\n"
            "protected has been renamed or removed. Fix or delete them, or the\n"
            "drift check will start failing at random:\n  "
            + "\n  ".join(unused),
            file=sys.stderr,
        )
        return 1

    if stale:
        print(
            f"\n{len(stale)} page(s) out of date with the examples that produce them:\n  "
            + "\n  ".join(stale)
            + "\n\nRun `python scripts/build_example_docs.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    print(f"\n{len(scripts)} page(s) {'checked' if args.check else 'written'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
